### ISSUE TITLE
Custom abstract types?

### ISSUE THREAD

**Issue by cambiata** [haxetink/tink_json#1]
Cool lib!

Is there a way to work with custom abstract types as well?
The following simple test gives an **Cannot handle AString** error:

```
 abstract AString(String) to String from String {
      inline public function new(string:String)  this = string;   
 }

 typedef Test =  { name:String, age:Int, email:AString };

class Main 
{   
    static function main() 
    {       
        var test:Test = { name:'Jonas', age:49, email:'jonasnys@gmail.com' };
        var json = Json.stringify(test);        
        var test2:Test = Json.parse(json);
    }   
}

```

**Comment by cambiata** [comment]
Hm, this seems to work as expected for direct casts...

```
 abstract AString(String) to String  from String {
      inline public function new(string:String)  this = string;   
}
```

...but not for class field casts - gives a "Cannot stringify AString" error:

```
 abstract AString(String)  {
      inline public function new(string:String)  this = string;   
      @:from static public function fromString(string:String) return new AString(string);
      @:to public function toString() return this;     
 }
```

**Comment by back2dos** [comment]
Yes, that decision was on purpose.

Consider this:

``` haxe
abstract Escaped(String) to String {
  inline function new(s) this = s;
  @:from static function ofString(s:String) 
    return new Escaped(StringTools.urlEscape(s));
}
```

Roundtripping that abstract through tink_json would then lead to double escaping, which is undesirable.

I do have plans to generally give developers control over how both classes and abstracts are read/written, which to my understanding should handle your use case too. I will close this again once that's added.

**Comment by back2dos** [comment]
Ok, Jonas. It's now possible as documented here: https://github.com/haxetink/tink_json#custom-abstracts

Hope that works for you ;)

**Comment by cambiata** [comment]
Seems great! Thanx!
