### ISSUE TITLE
[Writer.hx] wrong VObject serialization

### ISSUE THREAD

**Issue by profelis** [haxetink/tink_json#10]
Look like here
https://github.com/haxetink/tink_json/blob/master/src/tink/json/Writer.hx#L70-L83
should be `{}` brackets

**Comment by kevinresol** [comment]
Well I believe that function is unused. Do you have an example in what is actually wrong?

**Comment by kevinresol** [comment]
>

**Comment by back2dos** [comment]
The code is indeed never used. I plan to allow handling arbitrary data through properly typed JSON AST rather than `Dynamic`, but I'm currently in no particular hurry for that.

**Comment by profelis** [comment]
No, I just found this issue after code review 😄
