### ISSUE TITLE
Argument-less enum constructors?

### ISSUE THREAD

**Issue by Gama11** [haxetink/tink_json#14]
#3 suggests that this is supported. I couldn't find any example usage though - neither in the readme nor in the unit tests.

I tried these two variants:

```haxe
'{ "EnumValue": {} }'
'{ "EnumValue" }'
```

Both produce the same error:

>C:\HaxeToolkit\haxe\lib\tink_json/0,3,1/src/tink/json/macros/GenReader.hx:220: characters 23-29 : TestEnum cannot be called
C:\HaxeToolkit\haxe\lib\tink_json/0,3,1/src/tink/json/macros/Macro.hx:41: lines 41-43 : Defined in this class
source/Main.hx:3: characters 35-56 : Void should be TestEnum
C:\HaxeToolkit\haxe\lib\tink_json/0,3,1/src/tink/json/macros/Macro.hx:41: lines 41-43 : Defined in this class

Am I doing something wrong, or is this a regression?

Here's the full code:

```haxe
class Main {
    public static function main() {
        var o:TestEnum = tink.Json.parse('{ "EnumValue" }');
        trace(o);
    }
}

enum TestEnum {
    EnumValue;
}
```

**Comment by kevinresol** [comment]
I regret I didn't add a test 😕

**Comment by kevinresol** [comment]
Can you try this https://github.com/haxetink/tink_json/pull/16?
