### ISSUE TITLE
Fall back to haxe.Json for Dynamic values

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_json#18]
Sometimes we really need Dynamic in a JSON (say for some REST api we cannot change)

**Comment by back2dos** [comment]
Can you elaborate on that? What do you do with the `Dynamic` value once it is parsed?

**Comment by kevinresol** [comment]
Here: https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values#ValueRange

The 'values' field is actually `Array<Array<Dynamic>>`

In spreadsheets term, it is rows of data and each cell may contain mixed types: strings, numbers, etc

**Comment by back2dos** [comment]
I generally plan to use `tink.json.Value` for arbitrary JSON. The way I see it, it could cover your use case. Is that correct?

**Comment by kevinresol** [comment]
Is that for the "dynamic part" only or the whole json?
I think it would be more easy to use if it is just for the dynamic part

**Comment by back2dos** [comment]
The idea is to have it just for a part:

```haxe
var valueRange:{
  range: String,
  majorDimension: String,
  values: Array<tink.json.Value>
} = tink.Json.parse(theString);
```

And `tink.json.Representation` over `tink.json.Value` should work too, of course.

**Comment by kevinresol** [comment]
Yeah that looks good 👍
