### ISSUE TITLE
Parse as dynamic?

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_json#2]
I am just thinking will there be any chances that one wishes to parse whatever value regardless of its type?

``` haxe
Json.parse(("1":Int)); // works
Json.parse(("1":Dynamic)); // fails
```

**Comment by back2dos** [comment]
Well, that would seem somewhat contrary to what this library is aiming for.

If you do have a use case though, I'd be glad to discuss it ;)

**Comment by kevinresol** [comment]
Indeed. 
This is somewhat a made-up issue, https://github.com/haxetink/tink_typecrawler/issues/2 should be the more precise problem.
