### ISSUE TITLE
Serialized @:from

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_json#33]
In the context of trying to parse json in a query string (https://github.com/haxetink/tink_querystring/pull/7), the following was suggested:

>I mean I think we could make it so that tink.json.Serialized is a bit easier to use
>i.e. it could have a proper @:from cast so that you can just stick in the data
>and we could make sure it passes tink_querystring (you'll have to call theJsonField.parse() to get at the actual data)

I'm not sure which type were adding a `@:from` for? Stringly? I guess that would mean some changes to tink_querystring as well?

**Comment by kevinresol** [comment]
> I'm not sure which type were adding a `@:from` for

I think it means `tink.json.Serialized`?

**Comment by back2dos** [comment]
`Serialized` now has a `@:from macro`.
