### ISSUE TITLE
Question : keys autowrap

### ISSUE THREAD

**Issue by kiroukou** [haxetink/tink_json#36]
Hello,

Is there a way to ask/configure for a key autowrap with double quotes ?

Thanks

**Comment by back2dos** [comment]
What do you mean by that?

**Comment by kiroukou** [comment]
Being able to write the json without the double quotes around the keys
For example :
{name: "tom", city : "bordeaux"}

This is not json strict but also simplifiy the json writing for conf files.
I guess the macro could detect that and accept that with some parsing
configuration ?
Would be nice anyhow.



Le 16 oct. 2017 23:59, "Juraj Kirchheim" <notifications@github.com> a
écrit :

What do you mean by that?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/haxetink/tink_json/issues/36#issuecomment-337056215>,
or mute the thread

**Comment by back2dos** [comment]
I think in the end I prefer to do nothing here. In this case I would suggest a preprocessor that turns quirky JSON into strict one as needed.
