### ISSUE TITLE
Type not found

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_json#40]
I'm doing something wrong, but am not getting proper error reporting. I see the following messages:
````
.../haxe/macro/Expr.hx:542: characters 2-24 : Type not found : ProjectDefinition
.../tink/json/macros/Macro.hx:50: lines 50-52 : Defined in this class
````
The line in Expr refers to TPath: https://github.com/HaxeFoundation/haxe/blob/db5a1e4ddd2899befaaa5535124c518e581255d0/std/haxe/macro/Expr.hx#L542

The type is a typedef which I'm using to type tink_web responses and I don't see much wrong with it.
Any suggestions how I can debug this more easily? My guess is the typepath is constructed somewhere without path or correct module?

**Comment by benmerckx** [comment]
By the way, this only happens if the type param passed to tink.web.Router is an interface. If I pass it the actual implementation there's no problem.

**Comment by back2dos** [comment]
Any chance you could provide a minimal example? ^^

**Comment by benmerckx** [comment]
I finally managed to narrow it down! I was using some of the tink.sql types (in a typedef currently shared by input and a table definition) which use the `@:const` type parameters. Replacing `VarChar<255>` with `String` in the typedef made things compile. Not sure if this is really a compiler issue. Here's a minimal example:
````haxe
import tink.Json;

typedef VarChar<@:const L> = String;

typedef Input = {
  a: VarChar<255>
}

class Main {
  static function main() {
    var res: Input = tink.Json.parse('{"a": "text"}');
    trace(res);
  }
}
````
The errors are either 'does not define type' when the type is found in a module (as sub) or 'type not found' if it's not.
````
...haxe/macro/Expr.hx:542: characters 2-24 : Module Main does not define type I255
...tink/json/macros/Macro.hx:50: lines 50-52 : Defined in this class
````

**Comment by back2dos** [comment]
Fixed here: http://lib.haxe.org/p/tink_macro/0.16.2/
