### ISSUE TITLE
JS Target: Haxe 4 getting Cannot stringify Map<String, String>

### ISSUE THREAD

**Issue by hoseyjoe** [haxetink/tink_json#43]
In Haxe 4, JS or CPP target,  I'm getting

 Cannot stringify Map<String, String>

This does not occur in haxe 3.4.7

Error is displayed on the return line
`var eventArray = new Array<Map<String,String>>();
...
return Json.stringify(eventArray);`

let me know if you want a test project. This is not an issue for me today just looking toward the future

**Comment by kevinresol** [comment]
Because Map is moved to the haxe.ds package

**Comment by back2dos** [comment]
I wonder who's stupid idea that could have been ... [oh, wait](https://github.com/HaxeFoundation/haxe/issues/6593#issue-258730919) ...

**Comment by hoseyjoe** [comment]
So does that mean I can fix it?
`var eventArray = new Array<haxe.ds.Map<String,String>>(); ... return Json.stringify(eventArray);`
Or is it a tink_json issue? or a Haxe issue?

**Comment by kevinresol** [comment]
This is a tink_json issue, in the macro it should also handle `TType` for Map in Haxe 4.
(I guess the actual code resides in tink_typecrawler)

**Comment by back2dos** [comment]
You will need to update tink_macro and tink_typecrawler and it'll work ;)
