### ISSUE TITLE
"Conflict field" should be allowed in enum?

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_json#44]
This following will result in an error `conflict field "type"`
```haxe
class Main {
    static function main() {
        var o:E = tink.Json.parse('dummy');
    }
}

enum E {
    @:json({kind:'A'}) A(a:{type:Int});
    @:json({kind:'B'}) B(b:{type:String});
}
```

However since it is an enum, the parser should be able to branch into two separate parsing path according to the `kind` tag, even this may require parsing the object twice: 1st pass finds the tag and 2nd pass actually parses the enum payload.

**Comment by back2dos** [comment]
Hmm. Well, this one is not going to be fun ^^

Right now this:

```haxe
enum E {
    @:json({kind:'A'}) A(a:{int:Int});
    @:json({kind:'B'}) B(b:{string:String});
}
```

Just parses `{ kind: String, ?int:Int, ?string:String }` and then the enum is constructed from that. I'll have to think about it.

**Comment by kevinresol** [comment]
Yeah I know how it works ^^, I went through the code when I implemented `Option`
I think the 2-pass parsing is the easiest way to start with.

**Comment by kevinresol** [comment]
First pass produces: `{ kind: String, ?int:String, ?string:String }` where `int` and `string` are still unparsed json strings. Then determine enum constructor from there.
Second pass: pick the required params and parse into actual values

How does that sound?

**Comment by back2dos** [comment]
Actually I think we could parse ```{ kind: String, type: tink.json.Serialized<Any> }``` and then process that further.
