### ISSUE TITLE
How to work with random key names? 

### ISSUE THREAD

**Issue by grepsuzette** [haxetink/tink_json#45]
Can tink_json work with defined json objects held by a a random name? 
For instance suppose I have this json:

```
{
      "hungary": { "vol": 43.356, "p": 356.747 },
      "croatia": { "vol": 261.72, "p": 59.25 }
} 

```
Is it possible for json_tink to recognize any name such as "croatia" or "hungary" and put them e.g. in a Map<String, Something>?

From the doc I think it can recognize [ "somekey" => .. ] format, but of course I'm talking about pure json and haven't understood how to do that.

**Comment by back2dos** [comment]
You will have to use `haxe.DynamicAccess<{ vol:Float, p: Float }>` instead of `Map`. Haxe maps are serialized as an array of key-value-pairs ... try `trace(tink.Json.stringify(["foo" => 1, "bar" => 2]))` to see what that means ;)
