### ISSUE TITLE
infinite loop with haxe4 preview 5 ?

### ISSUE THREAD

**Issue by bablukid** [haxetink/tink_json#49]
when compiling a project , haxe compiler is stuck in an infinite loop.

If I call "haxe -v cagette.hxml" , I get a neverending log like this : 

Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\std/haxe/macro/Expr.hx:555)
Exiting macro tink.macro.Types.resolveDirectType

**Comment by back2dos** [comment]
It may well be possible, but a reproducible example would go a long way towards fixing it ;)

**Comment by back2dos** [comment]
Hmm, chances are this got solved in tink_macro. If not, please open a new ticket with code to reproduce the issue ;)
