### ISSUE TITLE
[cpp target] C1061: compiler limit: blocks nested too deeply

### ISSUE THREAD

**Issue by sh-dave** [haxetink/tink_json#52]
I'm encountering an issue with the cpp target (Windows 10, using vc2017), where the generated code won't compile. 

Test code is available in https://github.com/sh-dave/tink_json/tree/cpp-nesting-too-deep in `tests/T57Test.hx`. I tested with haxe `3.4` and `4.0.0-preview5`.

```shell
Compiling group: haxe
cl.exe -Iinclude -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -Fde:\projects\tink\tink_json\bin\cpp\obj/msvc19xp/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -arch:SSE2 -IC:/Users/dave/AppData/Roaming/haxe/haxelib/hxcpp/4,0,4/include -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_API_LEVEL=331(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -wd4996 ... tags=[haxe,static]
 - src/RunTests.cpp
 - src/__boot__.cpp
 - src/tink/unit/TestSuiteBuilder5.cpp
 - src/T57Test.cpp
 - src/ECSComponent.cpp
 - src/tink/json/Parser42.cpp
Error: Parser42.cpp
./src/tink/json/Parser42.cpp(10512): fatal error C1061: compiler limit: blocks nested too deeply
```

**Comment by back2dos** [comment]
Phew. Nice one. I'd kind of prefer gencpp to generally avoid that. Let's summon @hughsando to comment on whether that's realistic.

**Comment by kevinresol** [comment]
@sh-dave would you mind pasting that `Parser42.cpp` file to pastebin or something as a quick reference?

**Comment by sh-dave** [comment]
[Parser42.cpp.txt](https://github.com/haxetink/tink_json/files/2695146/Parser42.cpp.txt)

**Comment by back2dos** [comment]
Can you try if `-D tink_json_compact_code` makes a difference?

**Comment by hughsando** [comment]
Welcome to the world of codegen!
I'm not sure there is much I can do about this - unless it it a switch? I could not really tell.
I can only suggest working around it like:
```haxe
if (i<1)
   ...
else if (i<2)
  ...
else if (i<3)
  ...
else if (i<4)
  ...

to:

if (i<2) {
   if (i<1)
     ...
   else
     ....
}
else
{
 if (i<3)
     ...
   else
     ....
}

or:

if (i<1)
   return ...
if (i<2)
  return ...
if (i<3)
  return ...
if (i<4)
  return ...
```
So the elses do not build up.

**Comment by sh-dave** [comment]
Adding `tink_json_compact_code` also doesn't help.

```shell
Error: Parser2.cpp
./src/tink/json/Parser2.cpp(60): error C2660: 'tink::json::BasicParser_obj::g': function does not take 1 arguments
include\tink/json/BasicParser.h(57): note: see declaration of 'tink::json::BasicParser_obj::g'
```
[BasicParser.h.txt](https://github.com/haxetink/tink_json/files/2695841/BasicParser.h.txt)
[Parser2.cpp.txt](https://github.com/haxetink/tink_json/files/2695843/Parser2.cpp.txt)

Edit: This is an error in a different file though. The generated one for my test code still has a giant if cascade in it.

**Comment by back2dos** [comment]
It would seem that this works now (no idea what exactly changed, but oh well).
