### ISSUE TITLE
UInt support on JS

### ISSUE THREAD

**Issue by Gama11** [haxetink/tink_json#58]
`UInt` is currently not serialized correctly on all targets / has inconsistent results across targets.

```haxe
class Main {
	static function main() {
		var i:UInt = 0x80000000;
		trace(i); // 2147483648
		trace((i : Int)); // -2147483648

		var data:Data = {i: i};
		trace(tink.Json.stringify(data));
	}
}

typedef Data = {
	var i:UInt;
}
```

- for HL/CPP/Neko/Python/Java/Interp: `{"i":2147483648}`
- for JS: `{"i":-2147483648}`

Not sure if there's more targets with incorrect results.

**Comment by kevinresol** [comment]
I am not sure how to reliably parse string into a "Haxe UInt"

```haxe
public function parseUInt(v:String) {
    var ret:UInt = 0;
    for(i in 0...v.length) ret += Std.parseInt(v.charAt(i)) * Std.int(Math.pow(10, v.length - i - 1));
    return ret;
}

var u = parseUInt('2147483648'); // gives a native int of value 2147483648 on python
trace(u == 0x80000000); // false, because the latter is generated as -2147483648
```

Not sure what to expect here...

**Comment by kevinresol** [comment]
Keeping open for the python mystery

**Comment by back2dos** [comment]
Reported in https://github.com/HaxeFoundation/haxe/issues/9354
