### ISSUE TITLE
Option to omit null fields altogether

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_json#6]
I was using tink_json with my db, while my struct is something like `{?foo:String, ?bar:String}` and I try to perform an update with `tink.Json.stringify({foo:'new value'})`. The result is that tink_json encodes `bar=null` for me and causing a unintended update to the bar field in db. 

I think this option could be compile time so there will be not extra checks on runtime.
For the time being, I will fallback to `haxe.Json` :P

**Comment by kevinresol** [comment]
Since meta is now supported on anon, we can do it on a per-field basis:

``` haxe
typedef Data = {
  @:omitIfNull @:optional var foo:String;
  @:optional var bar:String;
}
```

**Comment by back2dos** [comment]
Optional fields are omitted when `null` now.
