### ISSUE TITLE
Can't cast hl.types.ArrayObj to hl.types.ArrayBytes_Int

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_json#61]
Can't cast hl.types.ArrayObj to hl.types.ArrayBytes_Int?

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/62120262-d614df80-b2f3-11e9-8691-b612f6b8fe79.png)

**Comment by back2dos** [comment]
Please provide a minimal example.

**Comment by sonygod** [comment]
class TestTinkJson 
	{

		public function new() 
		{
			var cards:Array<UInt>=[1,2,3];
		
			
			
			var a=tink.Json.stringify(cards);
			var b:Array<UInt>=tink.Json.parse(a);
		
			
			
		}
		
	}

**Comment by sonygod** [comment]
@back2dos  target:HashLink 1.10

**Comment by sonygod** [comment]
haxe.Json test pass,but tink.Json is error.

**Comment by sonygod** [comment]
@back2dos any news?
