### ISSUE TITLE
vscode IDE ERROR.

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_json#62]
![image](https://user-images.githubusercontent.com/748320/62268890-efd53480-b463-11e9-8d80-44cab32338da.png)

**Comment by back2dos** [comment]
Minimal example please ;)

**Comment by sonygod** [comment]
code can be compile,but this is only IDE error!

**Comment by sonygod** [comment]
I 've removed my test code use tink_json ,so ,there are no any examples now .
