### ISSUE TITLE
Handling exceptions ?

### ISSUE THREAD

**Issue by melMass** [haxetink/tink_json#64]
Hi,

What is the way to handle errors in tink-JSON?

I want to catch a **422** `UnprocessableEntity` error.

The following is not catch:
```haxe
try {
    out = tink.Json.parse(sys.io.File.getContent(path));
}
catch (excep:Any){
    Log.error(excep);
    return null;
}
```

Thanks

**Comment by back2dos** [comment]
The following works for me: 

```haxe
class Test {
  static function main() {
    var out:{ foo: Int } = null;
    try {
        out = tink.Json.parse('{"foo":true}');
    }
    catch (e:Any){
      trace(e);
    }
  }
}
```

With haxe 4.0.2, `haxe -lib tink_json --run Test` I get this output from the trace statement:

```
Test.hx:8: Error#422: number expected at character 7 in {"foo":  ---->  t  <----  rue} @ tink.json.BasicParser.die:354
```

**Comment by melMass** [comment]
Strange, here is the exact traceback:

<details>

```ruby
Uncaught exception: Error#422: missing field "engine_roots" at characters 0 - 160 in   ---->  {
  "current_engine" ...... _ENGINE"
  ]
}  <----   @ tink.json.BasicParser.die:354
Called from tink.core.TypedError.throwSelf(tink/core/Error.hx:92)
Called from tink.json.BasicParser.die(tink/json/Parser.hx:354)
Called from tink.json.Parser0.~parse0.1(tink/json/macros/GenReader.hx:187)
Called from tink.json.Parser0.parse0(tink/json/macros/GenReader.hx:123)
Called from tink.json.Parser0.parse(?:1)
Called from $Settings.load(Settings.hx:102)
Called from utils.$Constants.__constructor__(utils/Constants.hx:34)
Called from utils.$Constants.instance(utils/Constants.hx:12)
Called from utils.$CLIBase.__constructor__(utils/CLIBase.hx:15)
Called from commands.$MainCommand.__constructor__(commands/MainCommand.hx:8)
Called from fun$731(Main.hx:9)
```
</details>

**Comment by back2dos** [comment]
Could you please try to provide a reproducible example?

Alternatively you can try [`tink.Json.parse((theString:TheExpectedType))`](https://haxe.org/manual/expression-type-check.html). This will produce an [`Outcome<ExpectedType, Error>`](https://haxetink.github.io/tink_core/#/types/outcome).

That said, I would still appreciate instructions on how to reproduce this, so I can fix it ;)

**Comment by melMass** [comment]
Well pretty classic, but it works in isolation 🤣 : 
[Archive.zip](https://github.com/haxetink/tink_json/files/3890705/Archive.zip)

I'll check in project later today a keep you posted here

**Comment by melMass** [comment]
Yes, pretty much a simple user error there...

I was calling `json.Parse` at two different places in my code!
