### ISSUE TITLE
haxe.Utf8 is deprecated. Use UnicodeString instead.

### ISSUE THREAD

**Issue by edouard-lopez** [haxetink/tink_json#65]
I'm running an app with Haxe in a docker container:

	FROM haxe:4.0
	RUN apt-get update \
	    && apt-get install \
	            --yes \
	            --no-install-recommends \
	            --no-install-suggests \
	        php7.3 \
	        php7.3-mbstring  \
	    && rm -rf /var/lib/apt/lists/*
	
	RUN mkdir -p /usr/src/app
	WORKDIR /usr/src/app
	COPY *.hxml /usr/src/app/
	RUN yes | haxelib install all
	
	COPY . /usr/src/app/
	RUN haxe build.hxml
	
	CMD ["php", "-S", "0.0.0.0:8080", "-t", "www", "www/index.php"]
	

and with `tink_json` lib installed through the `build.xml`:

	-cp src
	-lib jstack 
	-lib tink_json
	-D JSTACK_HAXE_DEV
	-D JSTACK_FORMAT=vscode
	-debug
	-php www
	-main Main

When building my app:

	docker exec -it cagette-backend watch -n 2 haxe build.hxml

I got the following warnigs:

	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:130: characters 21-30 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:130: characters 21-37 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:161: characters 13-28 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:162: characters 5-14 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:162: characters 5-19 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:168: characters 15-24 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:168: characters 37-46 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:167: characters 23-32 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:167: characters 45-54 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:165: characters 23-32 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:165: characters 45-54 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:169: characters 16-25 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:169: characters 38-47 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:166: characters 23-32 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:166: characters 45-54 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:164: characters 33-42 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:164: characters 55-64 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:170: characters 16-25 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	/haxelib/tink_json/0,10,0/src/tink/json/Writer.hx:174: characters 13-23 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
	

How can I fix this warning? I `tink` up-to-date with `haxe:4.x`?

**disclaimer:** I'm new to haxe, so it might be trivial bug.

**Comment by kevinresol** [comment]
You can add `-D no-deprecation-warnings` to suppress them for the time being.
