### ISSUE TITLE
from/to + representation

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_json#74]
When an abstract relies on its from/to cast, and the underlying type is also an abstract type and relies on `Representation`, the compiler will expect the abstract type to be able to cast directly to such represention.

```
Error: Value should be tink.json.Representation<haxe.io.Bytes>
```

```haxe
import tink.Chunk;

class Main {
	static function main() {
		tink.Json.stringify((null:Value));
	}
}

abstract Value(Chunk) from Chunk to Chunk {
  // uncomment the following cast to fix
  // @:to inline function toRepresentation():tink.json.Representation<haxe.io.Bytes>
  //   return new tink.json.Representation(this.toBytes());
}
```

**Comment by back2dos** [comment]
We should probably deprecate `Representation` as `@:jsonStringify` has proper precedence and works on all types.
