### ISSUE TITLE
Do something about nulls in writer.

### ISSUE THREAD

**Issue by back2dos** [haxetink/tink_json#76]
This will throw when parsing:

```haxe
var o:{ foo:String } = { foo: null };
o = tink.Json.parse(tink.Json.stringify(o));
```

That's a little late.

**Comment by kevinresol** [comment]
The library expect users to type it as `{ foo:Null<String> }` because typecrawler has the `nullable` branch, no?

**Comment by back2dos** [comment]
Well, yeah. In this case I just had "unsafe" data that contained a `null` and the writer simply wrote it out. Not sure how to handle it, but ideally the the error would surface during serialization.

**Comment by kevinresol** [comment]
Wouldn't this be "solved" by enabling null safety?

**Comment by back2dos** [comment]
Well, the `null` came from `haxe.Json.parse(something)`. It might just as well be a database field or something. Perhaps for my case it would be sufficient to run `tink_validation` over the data, but I still wanna measure what the cost of checking in the writer might be. Maybe it's not even noticeable, otherwise it can be flagged.

**Comment by back2dos** [comment]
Hmm. I think in the end it's the user's responsibility to validate the data (via tink_validation or whatever).
