### ISSUE TITLE
Roundtrip of an enum doesn't work if one of the enum parameters is a haxe.ds.Option

### ISSUE THREAD

**Issue by jasononeil** [haxetink/tink_json#94]
Hello friends! I finally ran into a bug in this fantastic little library.

I have a type like this:

```
enum MyEvent {
	Boop(name:String, setting:haxe.ds.Option<String>);
}
```

When I try to do a roundtrip:

```
	final event = MyEvent.Boop("Carrots", Some("Green"));
	final string = tink.Json.stringify(event);
	final eventAgain:MyEvent = tink.Json.parse(string);
```

I get this error:

```
Error#422: Expected string at character 36 in ... "Carrots","setting":  ---->  {  <----  "Some":{"v":"Green"}
```

However, if I use a custom "Option" type:

```
enum MyOption<T> {
	Some(v:T);
	None;
}
enum MyEvent {
	Boop(name:String, setting:MyOption<String>);
}
```

then the roundtrip works. It seems something in the parser breaks specifically when doing a roundtrip of an enum with a `haxe.ds.Option` parameter. 

(I'm not sure how to get the tests on this repo running, so I'm not 100% sure this is a problem in the library rather than a problem on my end. Let me know if I'm missing something. I'd expect a failing test [to look like this](https://github.com/haxetink/tink_json/compare/jasono/roundtrip-with-option-issue?expand=1)).

**Comment by back2dos** [comment]
FWIW the tests can be run with `npm i && npx lix travix interp`, but yeah, looks good ;)

**Comment by jasononeil** [comment]
Nice! I’ll give that a go and see if I can get a fix together

**Comment by back2dos** [comment]
Well, it's a bit of a nasty edge case, due to the many different enum representations that are supported interfering with the fact that `Option` fields get special treatment too. But it works now ;)

**Comment by jasononeil** [comment]
Ah nice, thank you!
